language: ruby

bundler_args: --without debugger

cache: bundler
sudo: false

before_install:
  - gem --version

script: bundle exec rspec

rvm:
  - 2.1.5
  - 2.2
  - 2.3.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email:
    recipients:
      - ngiger@ywesee.com
      - yasaka@ywesee.com
      - zdavatz@ywesee.com
